language: node_js
node_js:
- node
- lts/*
before_install:
- bundle install
script:
- yarn build
- yarn lint
- yarn test:jest -- --coverage --coverageReporters lcov
after_success:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: dev.ukatama@gmail.com
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_NODE_VERSION = lts/*"
  api_key:
    secure: fHaYahA4wOYT7rf6uvFc7pvnFLXQ5skVKZilZvIuxpE4RarIYsySeMBp3mEvOmAOQJ42GHbsyODFvlKTvWKqrNnflmGl9dXojTEQDOYxWAwSJrjgCL1jeak2JWGZQ35SMIjG/WgtN7VfHyH19BjNBb+Yb4ujDgn5FdUMQhtfIrJU+QOVRjOI3aL2fctvftbKE0RSICzC1X80vrJVAczq/+sqIUUjv9mRwGFzyqVBsPg/BcSE2o+kqD8SWS1REirPQ2D4JTNM6wiq9czEklpZV6cP5+HaMQC2Ywd45uQYxFT0OfH4gRtom4aOVX/kGtqJIWP9P4+xRHTA2cvKTxIFOk1RfL6pmGTzymB8jmdFeCyyulVS76zNljFqbo+cUt8DMY8j/Oggy158km98U5fWRrdikb5GVXQRKiC29Zzo8nQv7yPfWuBbiG/3jfjOG3CJr7WlnyrcsOsnMzKhEpaqPp/ygK0MDmCPMLWBei9PcYDhhb1liBrjgTxR1u6uLxWdbAXPEhjEoFUkuG1akT/BVSWIVzsm3FGm+Ot2AKk1NRya5WUP1znEUQAt5oaM/SVrgC/XZUQv/NUK6SYjaa9JbkCPQ1Y9oEsbr1udBB7nl+D0ktDXNtFuf5ZH50yft4kxZhTXcvYfJ7uXb1rQ34uxbnAwEVZ+2KiJ2cC3EZLddqU=
notifications:
  email: false
  slack:
    secure: nY08EbRJFtL9+sUYM39Y1Agl+fmG2Tf7q3ti3AIC4g/2lrUSO/YQUMV4vLJ+Vt10HWL6n88EEclxD3mGjCg5wv07god5X3xm6deduy1JP41opdvAFAiNX3zoYh00GlZXsNZH1/jHn20Djz0hTxcPSosn4aDqR+in7xGJ1D1S11WKdqcFZ43XS0UxtRyoYzY/10z9AWh9MPZ0nfv6zJJlDT8GazSiQ4ArsFlHQ1gcbHf+/85eqa/HewmxCXSDsqpkbiQqRFQK1hHYlYhyrBKEZVaHADdPTLdEAGnwH6q0uayw7ydr4h0ubqt8EewwOO0qbn50IQUatzNDQhObY4lqgNgfM5xMQXryNcWB2+FKZI109OmuizXqyG7y4H3GbqJB93ueMEYndHuy363xsh+TvgPti92OWV08enCymFwHX2a62FpBTvCRbVhFWZDJhUyDvAYjV60CYkuJSdMPpNmbDWXAHLq0CcdYorIelSmnuQDUP9rZOmgb3rO4Wkhslx5P0C80warRVin1diaCKk8weVhpxsAGspIyspwfEOhLnXEiqvQMFPDnytZX0NlizAe3OXWx+G9SxOfFMrZSon0wlBlHCNWoeN4l8GbCJwsvznvRiYKawPBS3LFZrd+dz4gkvzdSZ15MPLwp3y9D74PYx8oCImthfDpDKbgg0Wks2R4=
