language: node_js
node_js:
- node
- lts/*
before_install:
- bundle install
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: dev.ukatama@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: sK+368Z7cpd6a81GUH865Xe6SFnP3idsh7KdgARkzHQ1Rws8XXvwTznt4wf2l4lBKmYqriRTOO+aKZo8eBBfFlqpyd/mjvrV4j+LrKhnj7i5OIliPy9ziDz2+j/2tMK1JzLvBkPlfaH2SmnDcE1L/IwdYuLGn9AA5lrknVta1onY9DWDzLnzS4xkW8kx7OCvRcx1LZcuO7U1JXYYRHr8lb5xAd9TzT9At+aOut2cIoqnBKGh+9/SBjTA8lD07nqsKP/8l/VzVFwJC/ECGixTG+b7voINB6X7+byoqT9Bf3DRzhgBflnNiRAAqQaQnNI1eGXPNfrCqJ3f4R3gjnecpqZsGs+8wyQwEgLnle+RIHyNk5d+BLRptlzgzG0mi85NgVs5Lup/C7VhQaQnByn8AHPMEHZqUA89yNdvrAfLAnWs6vDiX+4VtG6QoKxBFZh5SHFU1hh//q3xJalFk9zjFC4EZeM1y7AuINz4Ll6phy2B3P7Z+iTe9Axf1EBuFsOwCFWbVdEixSQBmXi1iGLARcTjvtNVSsm8q802cwEBfze7U0qQR6v/N1kElre7EF/htbwziHOlQ+dMLqYW9NxlrJ3Qtr2gwm9uwTGRp8hwIEmRZrPQs5jq/83n6Hrx5k9llFL3JtRsUl3MRj64OBcPVzhqbxx1hRX9ViAPHtyg/WI=
